### PR TITLE
Use rows instead of styles for text area.

### PR DESCRIPTION
**Pull request by aemkei**
This will change the layout, but get it down to 220 bytes.

@subzey @p01 @xem

### CODE REVIEW

**Comment by xem** [comment]
That's neat!
But also, very small (on screen)... :/
@p01 @subzey @aemkei - What do you prefer? small code or big UI ?

**Comment by aemkei** [comment]
Here is a preview: https://rawgithub.com/xem/miniCodeEditor/9ae0319854fe0ac91d4bbe60972e4fdf7fdf5135/modern.html

**Comment by xem** [comment]
Hey, I worked something quite similar but in 331 bytes, you can preview it in the branch "3+1", especially if you visit index.html, I think it's very neat.

**Comment by xem** [comment]
Here's the preview of my "mix":
https://rawgithub.com/xem/miniCodeEditor/b8cd7d027964bdcb43ab0decc0e8b074f1566b6b/index.html

**Comment by xem** [comment]
I made a dedicated "fork file" with your edit and mentioned it at the end of the homepage!
BTW: 210 bytes only!
http://xem.github.io/miniCodeEditor/

**Pull request closed without merging**
