### PR TITLE
Use `x` instead of `body`.

### PR DESCRIPTION
**Pull request by aemkei**
Down to 256.

### CODE REVIEW

**Comment by aemkei** [comment]
Down to 241.

**Comment by xem** [comment]
@aemkei @p01 @subzey I'm setting you as collaborators on this project, so you can push directly without having to send pull requests :)

**Comment by aemkei** [comment]
Thanks!

BTW: How about using `cols=20 rows=9` instead of 49%.

Would shrink it to 230.

**Comment by xem** [comment]
Okay!

BTW modern.html is currently broken on my Firefox and Chrome =(

I merged without testing... not sure if it's because of "x" or "lastChild"...

**Comment by aemkei** [comment]
Hmm, strange!

It is working for me on Chrome. What do you see when calling `e.lastChild`?

**Comment by aemkei** [comment]
Aah, I see why: 

Github adds a linebreak to the ond of the file which results in an empty text node.

Anyone know how to fix that?

**Comment by aemkei** [comment]
Looks like this happens for RAW files only: 

view-source:https://raw.github.com/xem/miniCodeEditor/gh-pages/modern.html

**Comment by xem** [comment]
I use Github for Windows and don't seem to have this problem...

**Comment by xem** [comment]
fixed

**Comment by aemkei** [comment]
Still see the new line and it is only working on my local machine.

**Comment by xem** [comment]
Weird! Anyway, http://xem.github.io/miniCodeEditor/modern.html works for me

**Comment by aemkei** [comment]
Now it works for me, too. Maybe it was a caching issue only.

**Pull request merged**
