### PR TITLE
Add placeholders

### PR DESCRIPTION
**Pull request by mdesantis**
This adds placeholders to the textareas, in order to identify respectively the HTML (H), the CSS (C) and the JS (J) textareas. Its cost is of 42 chars.

Feel free to modify it as you wish, or to reject it.

### CODE REVIEW

**Comment by xem** [comment]
Thanks for this initiative!
I'm afraid we can't keep it for the code golfing competition that is taking place here (sub-256 bytes),
But I won't reject it, I will add it in a "forks" folder and mention it in the homepage ;)
Is that ok for you?

**Comment by xem** [comment]
Done: http://xem.github.io/miniCodeEditor/

**Comment by mdesantis** [comment]
Thank you for the mentioning. I wish you a lot of under-256 bytes ideas :-)

**Comment by xem** [comment]
Oh yeah, I have lots of other code golfing ideas:
my past ideas are here: http://xem.github.io/?golfing
and here: http://xem.github.io/MiniSweeper/ (work in progress)
And my future ideas will arrive soon!

**Pull request closed without merging**
