### PR TITLE
259 bytes modern browsers

### PR DESCRIPTION
**Pull request by p01**

### CODE REVIEW

**Comment by p01** [comment]
I'm not sure how to edit multiple files and make a pull request with multiple commits straight from github.
Sorry, the setup on my laptop is sub-optimal.

[edit] Looks like I got the hang of it :p [/edit]

**Comment by subzey** [comment]
The whole `<script>` section may be safely moved to `<body onload="...">` and `onload=` replaced by IIFE. That would yield a lot of bytes.

**Comment by aemkei** [comment]
@subzey That would save some bytes, but mixed quotes and angle brackets might blow it up again.

**Comment by aemkei** [comment]
Anyway: Some great work here, again! 

And @xem: If you would ask me: I'd only provide the "modern" browser support here.

**Comment by xem** [comment]
Hi guys, thanks for your ideas

@subzey: I also thought of a body onload=IIFE but I couldn't keep it short with the onkeyup listener...

@aemkei: Yeah, was only experimenting on IE vs modern vs Firefox, but in the end, I will keep just one version.... hopefully Under 256b.

PS: modern.html doesn't work on IE11... It did before =(
(but I'm okay with that)

**Comment by p01** [comment]
Pretty sure we can get this down to 256b. The obvious 5b saving is to switch from base64 data: uri to simply `escape()` the markup but that might not for some characters.

@subzey Like @aemkei, I expect the escaping of the quotes and co to outdo the 1-3 bytes gain of swtiching from `<script>...</script>` to `<body onload="...">`. By append X times to the innerHTML we don't need to close the textarea and iframe which saves 4+ bytes overall ;)

**Comment by xem** [comment]
Neat :)

By the way, in modern.html, if I edit code and save the page on my desktop, that page is broken (it contains 6 textarea and 2 iframes)

Not a big deal, I'll just remove it from the features list... but do you know why it does that?

**Comment by aemkei** [comment]
256 for sure! See #2

**Pull request merged**
